// Build a Rocket V1.2
let name = prompt("Hello engineer! What is your name?");
alert("Welcome " + name + "! Time to build a rocket!");
let mass = Number(prompt("Enter rocket mass in pounds (lb) (e.g 1000 lb):"));
let thrust = Number(prompt("Enter engine thrust in pounds force (lbf)(e.g 2500 lbf):"));
let fuel = Number(prompt("Enter fuel load in pounds (lb)(e.g 800 lb):"));
let liftPower = thrust + fuel;
let requiredLift = mass * 2;
let extraLift = Math.max(0, liftPower - requiredLift);
let missingLift = Math.max(0, requiredLift - liftPower);
alert("Rocket summary");
alert("Mass = " + mass + " lb");
alert("Thrust = " + thrust + " lbf");
alert("Fuel = " + fuel + " lb");
alert("Lift power = " + liftPower + " lbf");
alert("Required lift = " + requiredLift + " lbf");
alert("Launch result:\n\nExtra lift available: " + extraLift + " lbf\nMissing lift needed: " + missingLift + " lbf");
alert("If your missing lift is 0, you reached orbit!!\nIf missing lift is greater than 0, the rocket crashed. :(");
let thrustWeightRatio = thrust / mass;
alert("Fun fact, " + "Your thrust to weight ratio is " + thrustWeightRatio.toFixed(2) + ".\nValues above 1.0 can lift off on Earth.(probably)");
let spaceSpeed = thrust * thrust;
alert("Another fun fact, \nIf you squared your thrust input,\nyour rocket would travel about " + spaceSpeed + " mph in space! (if it can get there in the firstplace..)");
alert("Nice job rocket building, " + name + "!!");
